### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by susl16c** [spatocode/Millionaire#1]
Uncaught ReferenceError: audience_wrapper is not defined
    at controller.js:223
When you press the hall help.
Do not lose answers when choosing 50/50
Prohibit re-pressing the call when it was used

**Comment by spatocode** [comment]
Hi @susl16c ! This is because the audience option functionality has not been implemented yet. You can feel free to contribute to this. Thanks!

**Comment by spatocode** [comment]
The errors has been fixed. Thank you!
